### ISSUE TITLE
Visa användarstatus som systemmeddelanden i chatflödet

### ISSUE THREAD

**Issue by itsabunny** [StudieGrupp2Java/ChatApp#15]
## Beskrivning

Som användare vill jag kunna se om andra användare är online eller offline för att veta om jag kan förvänta mig snabba svar i chatten.

## Acceptanskriterier

- [x] När en användare ansluter till chatten, ska ett meddelande visas som anger att de är online.
- [x] När en användare lämnar chatten eller är inaktiv i mer än 5 minuter, ska ett meddelande visas som anger att de är offline.
- [x] Varje användares status ska uppdateras i realtid och visas som systemmeddelanden i chatflödet.

## Tekniska noter

- Använd WebSockets för att hantera realtidsuppdateringar av användarnas status.
- Implementera en timeout-funktion för att sätta status till offline efter inaktivitet.
- Spara status i backend för att hålla korrekt status även om en användare återansluter.

## Definition of Done

- [x] Koden är skriven och testad
- [x] Dokumentation är uppdaterad
- [x] Pull request är skapad
- [x] Code review är genomförd
- [x] Alla tester går igenom

**Comment by adrjo** [comment]
Implementation idé: ett kommando /online
- Visar först alla aktiva och online användare
- Sedan inaktiva användare (online men har inte skickat meddelande på 5 min)
- Sist alla offline användare, med ett meddelande (last seen 7 hours ago)
